version: "3"
services:
    server:
        build: ./server
        entrypoint:
            - flask
            - run
            - --host=0.0.0.0
        environment:
            FLASK_DEBUG: 1
            FLASK_APP: ./server.py
        ports: 
            - "5000:5000"
            - "5678:5678"
        volumes: ['./server:/code']